// English content of the five games. The French content lives at the top of each file in www/jeux/.
// FIGURES_EN, EVENTS_EN and PLACES_EN follow the exact order of their French lists.
// WORDS_EN and DECKS_EN are independent lists: English spellings and words differ.

/* ---------- Who am I? (same order as FIGURES in jeux/qui-suis-je.js) ---------- */
const FIGURES_EN = [
  { n: "Noah", r: "Genesis 6–9",
    c: ["I lived nine hundred and fifty years.", "After a long voyage, I planted a vineyard.", "I built an ark to survive the flood."],
    x: "Noah is the ancestor of all humanity after the flood. The covenant and the laws that bear his name concern all peoples." },
  { n: "Melchizedek", r: "Genesis 14:18-20",
    c: ["I was both king and priest.", "I brought bread and wine to a victor.", "King of Salem, I blessed Abram in the name of God Most High."],
    x: "The Talmud (Nedarim 32b) identifies him with Shem, son of Noah." },
  { n: "Jethro", r: "Exodus 2:16; 18",
    c: ["I had seven daughters who tended my flock.", "I acknowledged that the Lord is greater than all gods.", "Priest of Midian, I advised my son-in-law Moses to appoint judges."],
    x: "The Torah portion that tells of the giving of the Ten Commandments bears his name: Yitro." },
  { n: "Ruth", r: "Ruth 1:16; 2; 4:17",
    c: ["I gleaned ears of grain in the field of a man of Bethlehem.", "I said to my mother-in-law: “Your people shall be my people, and your God my God.”", "A Moabite, I am the great-grandmother of King David."],
    x: "Her book is read on Shavuot, the festival of the giving of the Torah." },
  { n: "Naaman", r: "2 Kings 5",
    c: ["A young captive from Israel served my wife and told her about a prophet.", "I immersed seven times in the Jordan.", "An Aramean general, I was healed of leprosy by the prophet Elisha."],
    x: "After his healing, he declares that there is no God in all the earth except in Israel (2 Kings 5:15)." },
  { n: "Job", r: "Job 1–2",
    c: ["I lived in the land of Uz.", "Three friends came to comfort me and sat seven days without speaking.", "I lost my wealth, my children and my health, without cursing God."],
    x: "The book presents him as a blameless and upright man who fears God, without connecting him to the people of Israel." },
  { n: "Cyrus", r: "Isaiah 45:1; Ezra 1",
    c: ["The prophet Isaiah calls me the Lord’s anointed.", "I returned the Temple vessels that had been carried off to Babylon.", "King of Persia, I allowed the exiles to rebuild the Temple in Jerusalem."],
    x: "His decree, around 538 BCE, ends the Babylonian exile." },
  { n: "The Queen of Sheba", r: "1 Kings 10:1-13",
    c: ["I arrived in Jerusalem with camels laden with spices, gold and precious stones.", "I put riddles to a king, and he answered them all.", "I came from afar to test the wisdom of Solomon."],
    x: "Impressed, she praises the Lord, the God of Solomon (1 Kings 10:9)." },
  { n: "Rahab", r: "Joshua 2; 6:22-25",
    c: ["My house was built into the city wall.", "I hid two spies under stalks of flax on my roof.", "In Jericho, a scarlet cord at my window saved my family."],
    x: "She acknowledges that the Lord is God “in heaven above and on earth below” (Joshua 2:11)." },
  { n: "Balaam", r: "Numbers 22–24",
    c: ["I came from Pethor, by the river.", "My donkey saw an angel before I did, and then she spoke to me.", "Hired by the king of Moab to curse Israel, I blessed it."],
    x: "His blessing “How goodly are your tents, O Jacob” is still recited on entering the synagogue." },
  { n: "Jonah", r: "Jonah 1–3",
    c: ["I boarded a ship at Jaffa to flee to Tarshish.", "I spent three days and three nights in the belly of a great fish.", "Sent to Nineveh, I saw a whole city repent."],
    x: "His book, read on Yom Kippur, shows that repentance is open to all peoples." },
  { n: "Abraham", r: "Genesis 11:31; 17:5; 18",
    c: ["I left Ur of the Chaldees with my father.", "I welcomed three visitors at the entrance of my tent.", "God changed my name and promised I would be the father of a multitude of nations."],
    x: "His name changes from Abram to Abraham: “father of a multitude of nations”." },
  { n: "Pharaoh’s daughter", r: "Exodus 2:5-10",
    c: ["I used to go down to bathe in the river with my maidens.", "I took pity on a baby crying in a basket.", "I adopted Moses and gave him his name."],
    x: "Tradition calls her Bitya (1 Chronicles 4:18; Megillah 13a)." },
  { n: "Hiram", r: "1 Kings 5:15-26",
    c: ["I was always a friend of King David.", "I sent cedars and cypresses from Lebanon by sea.", "King of Tyre, I helped Solomon build the Temple."],
    x: "He blesses the Lord for giving David a wise son (1 Kings 5:21)." },
  { n: "Nebuchadnezzar", r: "Daniel 2–3; 2 Kings 25",
    c: ["I dreamed of a huge statue with feet of iron and clay.", "I had three young men thrown into a fiery furnace.", "King of Babylon, I destroyed the First Temple in Jerusalem."],
    x: "The First Temple is destroyed in the 6th century BCE and the people of Judah are exiled to Babylon." },
  { n: "Esther", r: "Esther 2:7; 7",
    c: ["My other name is Hadassah.", "An orphan, I was raised by my cousin Mordecai.", "Queen of Persia, I foiled Haman’s plot against my people."],
    x: "The festival of Purim recalls this reversal." },
  { n: "Ebed-Melech", r: "Jeremiah 38:7-13; 39:15-18",
    c: ["I was a servant in the palace of King Zedekiah.", "I took old rags and ropes for a rescue.", "A Cushite, I pulled the prophet Jeremiah out of the cistern."],
    x: "God promises him his life, “because you have put your trust in Me” (Jeremiah 39:18)." },
  { n: "Hagar", r: "Genesis 16; 21:9-21",
    c: ["An angel found me by a spring in the desert.", "I called God “El-Roi”, the God who sees me.", "Egyptian maidservant of Sarai, I am the mother of Ishmael."],
    x: "God hears the voice of her son in the desert and promises to make him a great nation (Genesis 21:17-18)." },
  { n: "Elijah", r: "1 Kings 17–18; 2 Kings 2:11",
    c: ["Ravens brought me bread and meat.", "I challenged the prophets of Baal on Mount Carmel.", "I was taken up to heaven in a whirlwind."],
    x: "The prophet Malachi announces his return (Malachi 3:23)." },
  { n: "Daniel", r: "Daniel 1:7; 5; 6",
    c: ["In Babylon I was given the name Belteshazzar.", "I deciphered writing traced on the palace wall.", "I was thrown into the lions’ den."],
    x: "Part of his book is written in Aramaic." },
  { n: "Moses", r: "Exodus 3; 12–20",
    c: ["I tended my father-in-law’s flocks in Midian.", "I saw a bush that burned without being consumed.", "I led Israel out of Egypt and received the Torah at Sinai."],
    x: "The Torah says of him that he was the humblest man on earth (Numbers 12:3)." },
  { n: "David", r: "1 Samuel 16–17",
    c: ["I was the youngest son of Jesse of Bethlehem.", "I played the harp to soothe King Saul.", "With a sling, I defeated Goliath."],
    x: "Great-grandson of Ruth the Moabite, he makes Jerusalem his capital." },
  { n: "Joseph", r: "Genesis 37; 40–41",
    c: ["My father gave me a tunic that my brothers envied.", "I interpreted the dreams of two prisoners, then those of Pharaoh.", "Sold by my brothers, I became viceroy of Egypt."],
    x: "He saves Egypt and his own family from seven years of famine." },
  { n: "Solomon", r: "1 Kings 3; 6",
    c: ["I asked God for an understanding heart rather than riches.", "I settled the dispute of two mothers over one child.", "Son of David, I built the First Temple."],
    x: "In his dedication prayer he asks God to answer also the foreigner who comes to pray at the Temple (1 Kings 8:41-43)." }
];

/* ---------- The timeline (same order as EVENTS in jeux/frise.js) ---------- */
const EVENTS_EN = [
  { t: "The creation of Adam", w: "Genesis 1–2" },
  { t: "The flood", w: "Genesis 6–9" },
  { t: "The Tower of Babel", w: "Genesis 11" },
  { t: "Abram leaves Haran for Canaan", w: "Genesis 12" },
  { t: "The binding of Isaac", w: "Genesis 22" },
  { t: "Joseph is sold by his brothers", w: "Genesis 37" },
  { t: "The Exodus from Egypt", w: "Exodus 12–14" },
  { t: "The giving of the Torah at Sinai", w: "Exodus 19–20" },
  { t: "Joshua leads the crossing of the Jordan", w: "Joshua 3" },
  { t: "Ruth arrives in Bethlehem", w: "Ruth 1, in the time of the Judges" },
  { t: "Saul becomes the first king of Israel", w: "1 Samuel 10" },
  { t: "David reigns in Jerusalem", w: "2 Samuel 5, c. 1000 BCE" },
  { t: "Solomon builds the First Temple", w: "1 Kings 6, c. 960 BCE" },
  { t: "The kingdom splits in two", w: "1 Kings 12, c. 930 BCE" },
  { t: "Elijah confronts the prophets of Baal", w: "1 Kings 18, 9th century BCE" },
  { t: "Jonah preaches in Nineveh", w: "Jonah 3, 8th century BCE" },
  { t: "Fall of Samaria, exile of the ten tribes", w: "2 Kings 17, 722 BCE" },
  { t: "Destruction of the First Temple", w: "2 Kings 25, 586 BCE" },
  { t: "Decree of Cyrus", w: "Ezra 1, 538 BCE" },
  { t: "Dedication of the Second Temple", w: "Ezra 6, 516 BCE" },
  { t: "Nehemiah rebuilds the walls of Jerusalem", w: "Nehemiah 2–6, c. 445 BCE" },
  { t: "Alexander the Great conquers Judea", w: "332 BCE" },
  { t: "The Torah is translated into Greek (Septuagint)", w: "3rd century BCE" },
  { t: "Decrees of Antiochus IV against Judaism", w: "167 BCE" },
  { t: "The Maccabees purify the Temple", w: "164 BCE" },
  { t: "Pompey enters Jerusalem", w: "63 BCE" },
  { t: "Herod enlarges the Second Temple", w: "c. 20 BCE" },
  { t: "Destruction of the Second Temple", w: "70 CE" },
  { t: "Fall of Masada", w: "73 CE" },
  { t: "Bar Kokhba revolt", w: "132–135 CE" },
  { t: "Compilation of the Mishnah", w: "c. 200 CE" },
  { t: "Maimonides completes the Mishneh Torah", w: "c. 1180 CE" }
];

/* ---------- The map (same order as PLACES in jeux/carte.js) ---------- */
const PLACES_EN = {
  proche: [
    { n: "Jerusalem", d: "The city of the Temple, capital of King David.", r: "2 Samuel 5; 1 Kings 6" },
    { n: "Ur", d: "The city that Terah and his son Abram leave.", r: "Genesis 11:31",
      x: "Most commonly identified with Tell el-Muqayyar, in southern Iraq." },
    { n: "Haran", d: "The stopping place where Terah settles, and from which Abram sets out for Canaan.", r: "Genesis 11:31; 12:4" },
    { n: "Babylon", d: "The city of the Tower of Babel, and later of Judah’s exile.", r: "Genesis 11:9; 2 Kings 25" },
    { n: "Nineveh", d: "The great city of Assyria to which Jonah is sent.", r: "Jonah 1:2" },
    { n: "Shushan (Susa)", d: "The Persian capital of Esther and Nehemiah.", r: "Esther 1:2; Nehemiah 1:1" },
    { n: "Mount Ararat", d: "The region where the ark comes to rest after the flood.", r: "Genesis 8:4",
      x: "The Torah speaks of the “mountains of Ararat”, a whole region; the peak that bears the name today is part of it." },
    { n: "Damascus", d: "The city of Eliezer, Abram’s servant, and of the general Naaman.", r: "Genesis 15:2; 2 Kings 5" },
    { n: "Mount Sinai", d: "The mountain of the giving of the Torah.", r: "Exodus 19",
      x: "The point marks the traditional site (Jebel Musa); the exact location is debated." },
    { n: "Alexandria", d: "The Egyptian city where the Torah is translated into Greek.", r: "Megillah 9a" },
    { n: "The land of Goshen", d: "The region of Egypt where Jacob and his sons settle.", r: "Genesis 47:6" },
    { n: "Antioch", d: "The capital of the Seleucid kings, enemies of the Maccabees.", r: "1 Maccabees 3:37" },
    { n: "Ecbatana", d: "The city in Media where the decree of Cyrus is found.", r: "Ezra 6:2" }
  ],
  israel: [
    { n: "Jerusalem", d: "The city of the Temple, capital of King David.", r: "2 Samuel 5; 1 Kings 6" },
    { n: "Hebron", d: "The city of the Tomb of the Patriarchs, David’s first capital.", r: "Genesis 23; 2 Samuel 2:11" },
    { n: "Beersheba", d: "Abraham’s well, at the southern edge of the land.", r: "Genesis 21:31" },
    { n: "Shechem", d: "Abram’s first stop in Canaan.", r: "Genesis 12:6" },
    { n: "Jaffa", d: "The port where Jonah boards a ship to flee.", r: "Jonah 1:3" },
    { n: "Mount Carmel", d: "The mountain where Elijah confronts the prophets of Baal.", r: "1 Kings 18" },
    { n: "Tiberias", d: "The last seat of the Sanhedrin, on the shore of Lake Kinneret.", r: "Rosh Hashanah 31b" },
    { n: "Dan", d: "The northernmost city: “from Dan to Beersheba”.", r: "Judges 20:1" },
    { n: "Tyre", d: "The city of King Hiram, who supplies the cedars for the Temple.", r: "1 Kings 5:15-26" },
    { n: "Masada", d: "The fortress that fell after the destruction of the Second Temple.", r: "Josephus, The Jewish War VII" },
    { n: "Qumran", d: "The site of the Dead Sea Scrolls.", r: "Scrolls discovered from 1947 onward" },
    { n: "Mount Nebo", d: "The mountain from which Moses views the land.", r: "Deuteronomy 34:1" },
    { n: "Modi’in", d: "The town of Mattathias, where the Maccabean revolt begins.", r: "1 Maccabees 2:1" },
    { n: "Ashkelon", d: "One of the five cities of the Philistines.", r: "1 Samuel 6:17" },
    { n: "Megiddo", d: "The city where King Josiah falls.", r: "2 Kings 23:29" }
  ]
};
const MAP_TITLES_EN = { proche: "The Near East", israel: "The Land of Israel" };
// Names written on the maps, keyed by their French label
const MAP_LABELS_EN = {
  "Mer Méditerranée": "Mediterranean Sea", "Mer Rouge": "Red Sea", "Golfe Persique": "Persian Gulf", "Mer Caspienne": "Caspian Sea",
  "Nil": "Nile", "Euphrate": "Euphrates", "Tigre": "Tigris", "Mer Morte": "Dead Sea", "Kinnéret": "Kinneret", "Jourdain": "Jordan"
};

/* ---------- Mystery word (w = uppercase word of 4 to 7 letters, k = category) ---------- */
const WORDS_EN = [
  { w: "MOSES", k: "Character", x: "He leads Israel out of Egypt and receives the Torah at Sinai.", r: "Exodus 3; 19" },
  { w: "AARON", k: "Character", x: "Brother of Moses and first high priest.", r: "Exodus 28:1" },
  { w: "JONAH", k: "Character", x: "The prophet sent to Nineveh.", r: "Jonah 1:2" },
  { w: "DAVID", k: "Character", x: "The shepherd of Bethlehem who became king of Israel.", r: "1 Samuel 16" },
  { w: "RUTH", k: "Character", x: "The Moabite, great-grandmother of King David.", r: "Ruth 4:17" },
  { w: "NAAMAN", k: "Character", x: "The Aramean general healed by Elisha.", r: "2 Kings 5" },
  { w: "JETHRO", k: "Character", x: "The priest of Midian, father-in-law of Moses.", r: "Exodus 18" },
  { w: "CYRUS", k: "Character", x: "The king of Persia who allows the exiles to return.", r: "Ezra 1" },
  { w: "BALAAM", k: "Character", x: "The diviner who blesses Israel instead of cursing it.", r: "Numbers 22–24" },
  { w: "RAHAB", k: "Character", x: "She hides Joshua’s spies in Jericho.", r: "Joshua 2" },
  { w: "ESTHER", k: "Character", x: "The queen who saves her people from Haman’s plot.", r: "Esther 7" },
  { w: "DANIEL", k: "Character", x: "Thrown into the lions’ den, he comes out alive.", r: "Daniel 6" },
  { w: "ISAIAH", k: "Character", x: "The prophet of the house of prayer for all peoples.", r: "Isaiah 56:7" },
  { w: "ABRAHAM", k: "Character", x: "The father of a multitude of nations.", r: "Genesis 17:5" },
  { w: "ISAAC", k: "Character", x: "The son of Abraham and Sarah.", r: "Genesis 21:3" },
  { w: "JACOB", k: "Character", x: "The father of the twelve tribes, also named Israel.", r: "Genesis 32:29" },
  { w: "JOSEPH", k: "Character", x: "Sold by his brothers, he becomes viceroy of Egypt.", r: "Genesis 37; 41" },
  { w: "JOSHUA", k: "Character", x: "The successor of Moses, who leads Israel into Canaan.", r: "Joshua 1" },
  { w: "SAMUEL", k: "Character", x: "The prophet who anoints Saul, then David.", r: "1 Samuel 10; 16" },
  { w: "SOLOMON", k: "Character", x: "The king who builds the First Temple.", r: "1 Kings 6" },
  { w: "ELIJAH", k: "Character", x: "The prophet of Mount Carmel, taken up in a whirlwind.", r: "1 Kings 18; 2 Kings 2" },
  { w: "EZRA", k: "Character", x: "The scribe who brings exiles back from Babylon.", r: "Ezra 7" },
  { w: "HIRAM", k: "Character", x: "The king of Tyre, ally of David and Solomon.", r: "1 Kings 5:15" },
  { w: "BABEL", k: "Place", x: "The city of the tower and of the confusion of languages.", r: "Genesis 11:9" },
  { w: "NINEVEH", k: "Place", x: "The great city of Assyria that repents.", r: "Jonah 3" },
  { w: "ARARAT", k: "Place", x: "The mountains where the ark comes to rest.", r: "Genesis 8:4" },
  { w: "SINAI", k: "Place", x: "The mountain of the giving of the Torah.", r: "Exodus 19" },
  { w: "HEBRON", k: "Place", x: "The city of the Tomb of the Patriarchs.", r: "Genesis 23" },
  { w: "CARMEL", k: "Place", x: "The mountain where Elijah confronts the prophets of Baal.", r: "1 Kings 18" },
  { w: "JERICHO", k: "Place", x: "The first city taken by Joshua.", r: "Joshua 6" },
  { w: "CANAAN", k: "Place", x: "The land promised to Abraham and his descendants.", r: "Genesis 12:5-7" },
  { w: "EGYPT", k: "Place", x: "The land of slavery and of the Exodus.", r: "Exodus 12" },
  { w: "MIDIAN", k: "Place", x: "The land where Moses takes refuge and becomes a shepherd.", r: "Exodus 2:15" },
  { w: "MOAB", k: "Place", x: "The homeland of Ruth.", r: "Ruth 1:4" },
  { w: "ZION", k: "Place", x: "The hill of Jerusalem captured by David.", r: "2 Samuel 5:7" },
  { w: "EDEN", k: "Place", x: "The garden where God places the first man.", r: "Genesis 2:8" },
  { w: "TORAH", k: "Key word", x: "The Teaching: the five books of Moses.", r: "Deuteronomy 33:4" },
  { w: "FLOOD", k: "Key word", x: "The waters that cover the earth in the time of Noah.", r: "Genesis 7" },
  { w: "RAINBOW", k: "Key word", x: "The sign of the covenant with Noah and all humanity.", r: "Genesis 9:13" },
  { w: "RAVEN", k: "Key word", x: "The first bird Noah sends out of the ark.", r: "Genesis 8:7" },
  { w: "DOVE", k: "Key word", x: "The bird that brings Noah an olive leaf.", r: "Genesis 8:11" },
  { w: "OLIVE", k: "Key word", x: "The tree from which the dove brings back a leaf.", r: "Genesis 8:11" },
  { w: "MANNA", k: "Key word", x: "Israel’s food during forty years in the desert.", r: "Exodus 16" },
  { w: "SHOFAR", k: "Key word", x: "The horn sounded on Rosh Hashanah.", r: "Leviticus 23:24" },
  { w: "TEMPLE", k: "Key word", x: "The house of prayer for all peoples, in Jerusalem.", r: "Isaiah 56:7" },
  { w: "PSALM", k: "Key word", x: "A song of praise; the book contains one hundred and fifty.", r: "Book of Psalms" },
  { w: "SHABBAT", k: "Key word", x: "The seventh day, the day of rest.", r: "Genesis 2:2-3" },
  { w: "SHEMA", k: "Key word", x: "“Hear”: the first word of Israel’s declaration of faith.", r: "Deuteronomy 6:4" },
  { w: "MISHNAH", k: "Key word", x: "The collection of the oral law, compiled by Rabbi Yehudah HaNasi around 200 CE.", r: "Pirkei Avot 1:1" },
  { w: "TALMUD", k: "Key word", x: "The Mishnah and its commentary; the seven laws are discussed in it.", r: "Sanhedrin 56a" },
  { w: "PURIM", k: "Festival", x: "The festival that recalls the rescue of the Jews of Persia.", r: "Esther 9:26" },
  { w: "SUKKOT", k: "Festival", x: "The festival of booths, seven days in autumn.", r: "Leviticus 23:42" },
  { w: "MATZAH", k: "Key word", x: "The unleavened bread of Passover.", r: "Exodus 12:39" },
  { w: "EXODUS", k: "Key word", x: "The second book of the Torah: the departure from Egypt.", r: "Book of Exodus" },
  { w: "GENESIS", k: "Key word", x: "The first book of the Torah, Bereshit in Hebrew.", r: "Book of Genesis" },
  { w: "ALTAR", k: "Key word", x: "Noah builds one on leaving the ark.", r: "Genesis 8:20" }
];

/* ---------- Memory (hebreu: [Hebrew word, transliteration, meaning]; other decks: [card A, card B]) ---------- */
const DECKS_EN = {
  hebreu: { name: "Hebrew words", pairs: [
    ["שלום", "shalom", "Peace"], ["אמת", "emet", "Truth"], ["קשת", "keshet", "Bow"], ["תורה", "Torah", "Teaching"],
    ["צדקה", "tzedakah", "Justice"], ["ברית", "brit", "Covenant"], ["אור", "or", "Light"], ["מים", "mayim", "Water"],
    ["שמים", "shamayim", "Sky"], ["ארץ", "eretz", "Earth"], ["מלך", "melech", "King"], ["נביא", "navi", "Prophet"],
    ["תפילה", "tefillah", "Prayer"], ["חסד", "chesed", "Kindness"], ["חכמה", "chochmah", "Wisdom"], ["לב", "lev", "Heart"],
    ["יום", "yom", "Day"], ["לילה", "laylah", "Night"], ["עץ", "etz", "Tree"], ["הר", "har", "Mountain"],
    ["ים", "yam", "Sea"], ["לחם", "lechem", "Bread"], ["רוח", "ruach", "Breath"], ["קול", "kol", "Voice"],
    ["ספר", "sefer", "Book"], ["אהבה", "ahavah", "Love"], ["אמונה", "emunah", "Faith"], ["חיים", "chayim", "Life"],
    ["שמש", "shemesh", "Sun"], ["ירח", "yareach", "Moon"], ["כוכב", "kochav", "Star"], ["בית", "bayit", "House"],
    ["דרך", "derech", "Way"], ["עם", "am", "People"], ["תיבה", "tevah", "Ark"], ["מבול", "mabul", "Flood"],
    ["יונה", "yonah", "Dove"], ["זית", "zayit", "Olive tree"], ["ענן", "anan", "Cloud"], ["אב", "av", "Father"]
  ] },
  fetes: { name: "Festivals", pairs: [
    ["Passover", "The Exodus from Egypt"], ["Shavuot", "The giving of the Torah"], ["Sukkot", "The booths in the desert"],
    ["Rosh Hashanah", "The sounding of the shofar"], ["Yom Kippur", "The day of atonement"], ["Hanukkah", "The Maccabees’ victory"],
    ["Purim", "The scroll of Esther"], ["Tisha B’Av", "The destruction of the Temple"]
  ] },
  personnages: { name: "People", pairs: [
    ["Noah", "The ark"], ["Abraham", "Ur of the Chaldees"], ["Moses", "The burning bush"], ["Jonah", "Nineveh"],
    ["Ruth", "The fields of Boaz"], ["Naaman", "The Jordan"], ["Elijah", "Mount Carmel"], ["Cyrus", "The decree of return"],
    ["Jethro", "The judges of Israel"], ["Daniel", "The lions’ den"], ["Solomon", "The First Temple"], ["Esther", "Shushan"],
    ["David", "The sling"], ["Rahab", "Jericho"]
  ] }
};
