// English content of the quiz. The French content lives in index.html (CATS and Q).
// Q_EN follows the exact order of Q: same number of entries, and in each entry
// the first answer of `a` is the correct one, with the others in the same order as in French.
const CATS_EN = {
  torah:  { name: "Torah", desc: "The five books of Moses" },
  neviim: { name: "Prophets and Writings", desc: "Nevi’im and Ketuvim" },
  second: { name: "Second Temple", desc: "The intertestamental period" },
  fetes:  { name: "Jewish festivals", desc: "The festivals and their meaning" },
  lois:   { name: "The seven laws", desc: "The Noahide laws and their sources" },
  hebreu: { name: "Biblical Hebrew", desc: "Key words and ideas" }
};

const Q_EN = [
  // ---------- Torah ----------
  { q: "What sign does God give as the token of His covenant with Noah and every living creature?",
    a: ["The rainbow", "Circumcision", "Shabbat", "The olive branch"], r: "Genesis 9:12-13",
    x: "“I have set My bow in the cloud”: the rainbow (keshet) is the sign of a covenant made with all humanity, not only with Israel." },
  { q: "How many people enter the ark?",
    a: ["Eight", "Six", "Ten", "Twelve"], r: "Genesis 7:13",
    x: "Noah, his wife, his three sons (Shem, Ham and Japheth) and their three wives." },
  { q: "Which bird does Noah release first at the end of the flood?",
    a: ["The raven", "The dove", "The eagle", "The sparrow"], r: "Genesis 8:6-12",
    x: "The raven flies back and forth until the waters dry up. The dove is sent only afterwards, three times." },
  { q: "On which mountains does the ark come to rest?",
    a: ["The mountains of Ararat", "Mount Sinai", "Mount Moriah", "Mount Carmel"], r: "Genesis 8:4",
    x: "In the seventh month, on the seventeenth day of the month." },
  { q: "Which king of Salem, “priest of God Most High”, blesses Abram?",
    a: ["Melchizedek", "Abimelech", "Amraphel", "Balak"], r: "Genesis 14:18-20",
    x: "The Talmud (Nedarim 32b) identifies Melchizedek with Shem, son of Noah: a non-Israelite who served the one God." },
  { q: "Which priest of Midian advises Moses to appoint judges over the people?",
    a: ["Jethro (Yitro)", "Balaam", "Aaron", "Caleb"], r: "Exodus 18:13-26",
    x: "The Torah portion that contains the giving of the Ten Commandments bears his name: Yitro." },
  { q: "Which non-Israelite diviner is hired to curse Israel, but ends up blessing it?",
    a: ["Balaam", "Jethro", "Og", "Sihon"], r: "Numbers 22–24",
    x: "Balak, king of Moab, sends for him. His blessing “How goodly are your tents, O Jacob” (Numbers 24:5) is still recited on entering the synagogue." },
  { q: "From which city does Abram set out with his father Terah?",
    a: ["Ur of the Chaldees", "Nineveh", "Babel", "Damascus"], r: "Genesis 11:31; 12:1-4",
    x: "Terah leaves Ur for Canaan but stops in Haran. It is from Haran that Abram sets out after the call “Lech lecha”." },
  { q: "Where does the building of a tower lead to the confusion of languages?",
    a: ["Babel", "Sodom", "Nineveh", "Jericho"], r: "Genesis 11:1-9",
    x: "In the plain of Shinar. The Torah links the name Babel to the verb balal, “to confuse”." },
  { q: "Who are the three sons of Noah?",
    a: ["Shem, Ham and Japheth", "Cain, Abel and Seth", "Isaac, Ishmael and Midian", "Reuben, Simeon and Levi"], r: "Genesis 6:10; 9:19",
    x: "“From these the whole earth was populated”: all peoples are therefore Bnei Noah, children of Noah." },

  // ---------- Prophets and Writings ----------
  { q: "To which great non-Jewish city is the prophet Jonah sent?",
    a: ["Nineveh", "Babylon", "Tyre", "Damascus"], r: "Jonah 1:2; 3:5-10",
    x: "The people of Nineveh repent and the city is spared. The book of Jonah is read on the afternoon of Yom Kippur." },
  { q: "Which Aramean general, healed of leprosy, declares that there is no God except in Israel?",
    a: ["Naaman", "Hazael", "Ben-Hadad", "Sisera"], r: "2 Kings 5:1-15",
    x: "After immersing seven times in the Jordan at Elisha’s word, Naaman renounces other gods. He is often cited as a model for non-Jewish monotheists." },
  { q: "Which Moabite woman is the great-grandmother of King David?",
    a: ["Ruth", "Orpah", "Naomi", "Rahab"], r: "Ruth 4:13-17",
    x: "Ruth marries Boaz; their son Obed is the father of Jesse, father of David. The book is read on Shavuot." },
  { q: "Which prophet announces: “My house shall be called a house of prayer for all peoples”?",
    a: ["Isaiah", "Jeremiah", "Ezekiel", "Amos"], r: "Isaiah 56:6-7",
    x: "The passage speaks of the “sons of the foreigner” who attach themselves to the Lord." },
  { q: "Which prophet announces: “On that day the Lord shall be one and His name one”?",
    a: ["Zechariah", "Malachi", "Hosea", "Joel"], r: "Zechariah 14:9",
    x: "This verse concludes the Aleinu prayer, recited at the end of every service." },
  { q: "Which Persian king allows the exiles to return and rebuild the Temple in Jerusalem?",
    a: ["Cyrus", "Nebuchadnezzar", "Darius the Mede", "Ahasuerus"], r: "Ezra 1:1-3; Isaiah 45:1",
    x: "His decree dates from about 538 BCE. Isaiah calls him God’s “anointed” (mashiach)." },
  { q: "In which book does the name of God never appear?",
    a: ["Esther", "Ruth", "Jonah", "Lamentations"], r: "Book of Esther; Chullin 139b",
    x: "Tradition reads a hidden presence into it: the Talmud links the name Esther to the verse “I will hide My face” (Deuteronomy 31:18)." },
  { q: "How many books does the Hebrew Bible contain according to the traditional Jewish count?",
    a: ["24", "22", "39", "12"], r: "Bava Batra 14b (order of the books)",
    x: "The content is the same as the 39 books of some editions, but the twelve minor prophets form a single book, as do Samuel, Kings, Chronicles and Ezra-Nehemiah. Josephus counted 22." },
  { q: "Which queen comes to test Solomon with riddles?",
    a: ["The Queen of Sheba", "Jezebel", "Vashti", "Athaliah"], r: "1 Kings 10:1-13",
    x: "Impressed by his wisdom, she praises the Lord, the God of Solomon (1 Kings 10:9)." },
  { q: "In which language are part of the book of Daniel and part of Ezra written?",
    a: ["Aramaic", "Greek", "Persian", "Akkadian"], r: "Daniel 2:4–7:28; Ezra 4:8–6:18",
    x: "Aramaic was the administrative language of the Persian empire and the everyday language of the Jews after the exile." },

  // ---------- Second Temple ----------
  { q: "According to the Mishnah, to whom do the last prophets hand down the Torah?",
    a: ["The men of the Great Assembly", "The Maccabees", "The Essenes", "Herod’s Sanhedrin"], r: "Pirkei Avot 1:1",
    x: "The Great Assembly (Anshei Knesset HaGedolah), active at the start of the Persian period, is the link between the prophets and the sages." },
  { q: "Which conqueror brings Judea under Greek rule around 332 BCE?",
    a: ["Alexander the Great", "Antiochus III", "Ptolemy I", "Pompey"], r: "Josephus, Antiquities XI, 8",
    x: "At his death in 323 BCE his empire is divided: Judea first passes to the Ptolemies of Egypt, then to the Seleucids of Syria around 200 BCE." },
  { q: "Which Greek translation of the Torah is made in Alexandria in the 3rd century BCE?",
    a: ["The Septuagint", "Targum Onkelos", "The Vulgate", "The Peshitta"], r: "Letter of Aristeas; Megillah 9a",
    x: "The Talmud tells that Ptolemy gathered 72 sages in 72 separate houses, and that they all produced the same translation." },
  { q: "Which Seleucid king forbids the practice of Judaism around 167 BCE?",
    a: ["Antiochus IV Epiphanes", "Alexander the Great", "Ptolemy II", "Herod the Great"], r: "1 Maccabees 1:41-64",
    x: "He installs a pagan cult in the Temple. His policy triggers the Maccabean revolt." },
  { q: "Which priest settled in Modi’in, father of Judah Maccabee, starts the revolt?",
    a: ["Mattathias (Matityahu)", "John Hyrcanus", "Eleazar", "Simon the Just"], r: "1 Maccabees 2:1-28",
    x: "He refuses to sacrifice to idols and takes refuge in the hills with his five sons." },
  { q: "Which festival commemorates the rededication of the Temple by the Maccabees?",
    a: ["Hanukkah", "Purim", "Sukkot", "Tu BiShvat"], r: "1 Maccabees 4:52-59; Shabbat 21b",
    x: "On the 25th of Kislev, around 164 BCE. The books of Maccabees are not part of the Hebrew Bible; the Talmud relates the miracle of the cruse of oil." },
  { q: "What is the name of the dynasty descended from the Maccabees, which rules Judea until 37 BCE?",
    a: ["The Hasmoneans", "The Herodians", "The Seleucids", "The Ptolemies"], r: "Josephus, Antiquities XII–XIV",
    x: "The name is said to come from an ancestor of Mattathias, Hasmon. The dynasty ends when Herod, backed by Rome, takes Jerusalem." },
  { q: "Which Roman general enters Jerusalem in 63 BCE?",
    a: ["Pompey", "Titus", "Julius Caesar", "Vespasian"], r: "Josephus, Antiquities XIV, 4",
    x: "Called in to arbitrate between the Hasmonean brothers Hyrcanus II and Aristobulus II, he places Judea under Roman control." },
  { q: "Which is the only biblical book preserved in full among the Dead Sea Scrolls?",
    a: ["Isaiah", "Genesis", "Psalms", "Daniel"], r: "Great Isaiah Scroll (1QIsaᵃ)",
    x: "Copied in the 2nd century BCE and discovered in 1947 in a cave at Qumran, it is more than a thousand years older than the Aleppo Codex." },
  { q: "Which sage of Jerusalem writes, around 180 BCE, a book of wisdom that the Talmud sometimes quotes?",
    a: ["Ben Sira", "Philo of Alexandria", "Josephus", "Hillel the Elder"], r: "Chagigah 13a",
    x: "Written in Hebrew, the book did not enter the Tanakh but was preserved in Greek. Hebrew fragments were found in the Cairo Genizah and at Masada." },

  // ---------- Jewish festivals ----------
  { q: "Which instrument is sounded on Rosh Hashanah?",
    a: ["The shofar", "The silver trumpets", "The harp", "The tambourine"], r: "Leviticus 23:24; Rosh Hashanah 16a",
    x: "The Torah calls this day a “day of blasting” (Yom Teruah). A ram’s horn is preferred, recalling the ram offered in place of Isaac." },
  { q: "Rosh Hashanah, the Jewish New Year, falls on the first day of which month?",
    a: ["Tishrei", "Nisan", "Elul", "Kislev"], r: "Leviticus 23:24",
    x: "The Torah calls it “the seventh month”: months are counted from Nisan, the month of the Exodus, but the count of years changes in Tishrei." },
  { q: "How long does the Yom Kippur fast last?",
    a: ["About 25 hours", "12 hours", "Three days", "One week"], r: "Leviticus 23:27-32",
    x: "The Torah sets it from one evening to the next. It begins before sunset and ends at nightfall the following day." },
  { q: "During Sukkot, people live in a booth for seven days. In memory of what?",
    a: ["Israel’s shelters in the desert", "The exile in Babylon", "Noah’s ark", "The building of the Temple"], r: "Leviticus 23:42-43",
    x: "Each generation is thus reminded that Israel lived in temporary shelters after leaving Egypt." },
  { q: "According to the Talmud, what do the 70 bulls offered in the Temple during Sukkot represent?",
    a: ["The seventy nations of the world", "The seventy elders of Israel", "The seventy years of exile", "The seventy years of a human life"], r: "Numbers 29:12-34; Sukkah 55b",
    x: "From 13 bulls on the first day down to 7 on the seventh, 70 in all, offered for all the peoples. Zechariah foretells that the nations will go up to Jerusalem to celebrate Sukkot (Zechariah 14:16)." },
  { q: "Which food is forbidden during Passover?",
    a: ["Leavened bread (chametz)", "Meat", "Wine", "Salt"], r: "Exodus 12:15-20, 39",
    x: "Matzah, unleavened bread, is eaten: at the Exodus the dough had no time to rise." },
  { q: "Which event does tradition associate with Shavuot?",
    a: ["The giving of the Torah at Sinai", "The Exodus from Egypt", "The dedication of the Temple", "The crossing of the Jordan"], r: "Exodus 19:1; Shabbat 86b",
    x: "The Torah makes it the festival of first fruits, seven weeks after Passover. Tradition celebrates the giving of the Torah on it, and the book of Ruth is read." },
  { q: "Which book is read on Purim?",
    a: ["The scroll of Esther", "The book of Ruth", "Lamentations", "The Song of Songs"], r: "Esther 3:7; 9:20-28",
    x: "Purim celebrates the rescue of the Jews of the Persian empire from Haman’s plot. Its name comes from “pur”, the lot that Haman cast." },
  { q: "According to the Mishnah, Tu BiShvat is the new year of what?",
    a: ["Trees", "Kings", "Cattle", "Festivals"], r: "Mishnah Rosh Hashanah 1:1",
    x: "The Mishnah counts four new years. The one for trees, on the 15th of Shevat, is used to calculate the tithes on fruit." },
  { q: "Which fast recalls the destruction of both Temples in Jerusalem?",
    a: ["The 9th of Av (Tisha B’Av)", "Yom Kippur", "The Fast of Esther", "The Fast of Gedaliah"], r: "Mishnah Taanit 4:6",
    x: "According to the Mishnah, the First and Second Temples were destroyed on this same date. The book of Lamentations is read." },

  // ---------- The seven laws ----------
  { q: "How many commandments does rabbinic tradition give to the descendants of Noah?",
    a: ["Seven", "Ten", "Thirteen", "Six hundred and thirteen"], r: "Sanhedrin 56a",
    x: "To establish courts, and to refrain from blasphemy, idolatry, forbidden relations, murder, theft and eating flesh from a living animal." },
  { q: "In which tractate of the Talmud are the seven laws listed and discussed?",
    a: ["Sanhedrin", "Berakhot", "Shabbat", "Pesachim"], r: "Sanhedrin 56a–60a",
    x: "This tractate deals with courts and criminal law. The seven laws are discussed there over several pages." },
  { q: "Which of the seven laws is an active obligation rather than a prohibition?",
    a: ["Establishing courts (Dinim)", "Not stealing (Gezel)", "Not blaspheming", "Not practising idolatry"], r: "Maimonides, Laws of Kings 9:14",
    x: "Every society must appoint judges to enforce the other six laws. The authorities debate its exact scope." },
  { q: "What does the prohibition called “ever min ha-chai” refer to?",
    a: ["Eating a limb torn from a living animal", "Consuming the blood of fish", "Hunting for pleasure", "Eating meat on Shabbat"], r: "Genesis 9:4",
    x: "After the flood, meat is permitted to Noah, but not flesh taken from an animal that is still alive." },
  { q: "According to Maimonides, which law does Noah receive in addition to the six given to Adam?",
    a: ["The prohibition of a limb from a living animal", "The prohibition of murder", "The obligation to establish courts", "The prohibition of theft"], r: "Maimonides, Laws of Kings 9:1",
    x: "Meat was not permitted to Adam. When it is permitted to Noah, the prohibition of a limb from a living animal is added." },
  { q: "From which verse does the Talmud derive all seven laws?",
    a: ["Genesis 2:16", "Genesis 9:1", "Exodus 20:2", "Deuteronomy 6:4"], r: "Sanhedrin 56b",
    x: "“And the Lord God commanded the man, saying: Of every tree of the garden you may eat.” Rabbi Yochanan links each word of the verse to one of the laws." },
  { q: "What does the expression “Birkat Hashem” mean in the list of the seven laws?",
    a: ["The prohibition of blasphemy", "The blessing before a meal", "The morning prayer", "An oath before a court"], r: "Sanhedrin 56a",
    x: "Literally “blessing the Name”: a euphemism used out of respect for the act of cursing God." },
  { q: "Which verse given to Noah is the basis for the prohibition of murder?",
    a: ["“Whoever sheds the blood of man, by man shall his blood be shed”", "“Be fruitful and multiply”", "“You shall love your neighbour as yourself”", "“Hear, O Israel”"], r: "Genesis 9:6",
    x: "The verse continues: “for in the image of God He made man”. Every human life bears that image." },
  { q: "What does Maimonides call a non-Jew who keeps the seven laws because God commanded them?",
    a: ["One of the pious of the nations of the world", "A convert (ger tzedek)", "A Levite", "A nazirite"], r: "Maimonides, Laws of Kings 8:11",
    x: "He is counted among the chasidei umot ha-olam and has a share in the world to come." },
  { q: "The prohibition of “gezel” concerns:",
    a: ["Theft", "Lying", "Slander", "Working on Shabbat"], r: "Sanhedrin 57a; Laws of Kings 9:9",
    x: "It covers theft, robbery and any unjust taking of another’s property, even of very small value." },

  // ---------- Biblical Hebrew ----------
  { q: "What does “Bereshit”, the first word of the Torah, mean?",
    a: ["In the beginning", "In the name of God", "These are the generations", "And God said"], r: "Genesis 1:1",
    x: "The first book bears this name: in Hebrew, each book of the Torah is named after one of its first words." },
  { q: "What does the Hebrew word “keshet” mean?",
    a: ["Bow (and rainbow)", "Covenant", "Flood", "Dove"], r: "Genesis 9:13",
    x: "The same word means the hunter’s bow and the rainbow. Covenant is brit, flood is mabul, dove is yonah." },
  { q: "Tanakh is an acronym. What do its three letters stand for?",
    a: ["Torah, Nevi’im, Ketuvim", "Talmud, Nevi’im, Kabbalah", "Torah, Nehemiah, Kohelet", "Tefillah, Nedarim, Ketubot"], r: "Tanakh",
    x: "The Teaching, the Prophets and the Writings: the three parts of the Hebrew Bible." },
  { q: "How many letters are there in the Hebrew alphabet?",
    a: ["22", "26", "24", "28"], r: "Psalm 119",
    x: "Five of them also have a final form. Psalm 119 has 22 stanzas, one for each letter." },
  { q: "What does “Shema”, the first word of the Jewish declaration of faith, mean?",
    a: ["Hear", "Peace", "Praise", "Remember"], r: "Deuteronomy 6:4",
    x: "“Hear, O Israel: the Lord is our God, the Lord is one.” The oneness of God is also at the heart of the faith of the Bnei Noah." },
  { q: "What does “Bnei Noah” mean?",
    a: ["The children of Noah", "The righteous of Noah", "The people of the ark", "The new believers"], r: "Genesis 9:19",
    x: "All humanity descends from Noah. The term refers in particular to non-Jews who commit to keeping the seven laws." },
  { q: "What does “emet” mean?",
    a: ["Truth", "Mother", "Faith", "Life"], r: "Shabbat 55a",
    x: "The Talmud calls it the seal of the Holy One, blessed be He. Its letters (alef, mem, tav) open, stand in the middle of, and close the alphabet." },
  { q: "“Hallelu-Yah” means:",
    a: ["Praise Yah (the Lord)", "God is great", "So be it", "Blessed be He"], r: "Psalms 146–150",
    x: "Yah is a shortened form of the divine name. The expression opens and closes each of the last five psalms." },
  { q: "What does the root of “tzedakah”, often translated as “charity”, mean?",
    a: ["Justice", "Pity", "Offering", "Forgiveness"], r: "Deuteronomy 16:20",
    x: "“Tzedek, tzedek tirdof”: justice, justice shall you pursue. Helping the poor is a duty of justice more than an act of generosity." },
  { q: "What does “Torah” mean in its first sense?",
    a: ["Teaching", "Penal code", "Scroll", "Holy book"], r: "Root yod-resh-heh",
    x: "The word comes from a root meaning “to instruct, to point the way”. Translating it only as “Law” falls short." }
];
